### ISSUE TITLE
Dark mode with UI Changes GsSoC'23

### ISSUE THREAD

**Issue by Nikhil1017** [group-patronage/group-patronage#7]
1) Implement Dark mode with Toggle button using Reactjs with Tailwind.
2) Make Search bar more visible.
3) Make changes to some existing fonts to Improve visibility.

**Comment by amilali** [comment]
I am willing to work on this issue

**Comment by Kali-Decoder** [comment]
can i contribute to this ??

**Comment by chaitanyarora** [comment]
Can I contribute to this as well?

**Comment by GVishnudhasan** [comment]
I am proficient in React.js and have experience working with Tailwind CSS. 

Here is my approach: 

1. Implementing Dark Mode: Utilize React state management to toggle between light and dark themes. Use Tailwind CSS classes and utility functions to style the components based on the selected theme. Provide a toggle button that triggers the theme change and updates the UI accordingly.

2. Enhancing Search Bar Visibility: Apply a visually appealing design to the Search Bar component to make it stand out. Utilize Tailwind CSS classes to adjust the size, color, and placement of the Search Bar. Implement hover effects or animation to draw attention to the Search Bar.

3. Font Changes for Improved Visibility: Identify the fonts used in the project and evaluate their legibility and visibility. Select more suitable fonts that enhance readability, especially for different screen sizes. Update the font styles and sizes in the relevant components to ensure optimal visibility. 
 
I am confident in my ability to execute these tasks effectively and deliver high-quality results. I am dedicated to following the project guidelines, collaborating with the team, and ensuring a seamless integration of the proposed features. I kindly request your consideration in assigning me this issue so that I can contribute to the project.

**Comment by pratyush-ksingh** [comment]
I would like to work on this project under GSSoc'23, please assign it to me.

**Comment by pranavs1205** [comment]
can u assign me this issue? I have good amount of knowledge in Reactjs.
